# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f780c51c45010f2800ec52643efa07b92b93fce262509f27c36f04a5233663fcf6f98bda13e6a601af912ffef4030736c8a62b75d03d8c10d3ae231603648d0

test:
  secret_key_base: 5fa00b185ca00f2778bbab315b90bfc18a00f95451d8444b5b305a122581a87033ad6c8398661b5b8b3269ae18b57929edbe041276872dce3d0efa0a5bf7bfda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
